SELECT SUM(S.PRICEPERUNIT*S.QUANTITY) AS TOTAL_ONSALE_REVENUE FROM PRODUCTS AS P
INNER JOIN SALES AS S ON S.PRODUCTID = P.PRODUCTID
WHERE P.ONSALE LIKE 1;

SELECT SUM(S.PRICEPERUNIT*S.QUANTITY) AS TOTAL_GAME_REVENUE FROM SALES AS S
INNER JOIN PRODUCTS AS P ON P.PRODUCTID = S.PRODUCTID
INNER JOIN categories AS C ON C.CategoryID = P.CategoryID
WHERE C.NAME LIKE 'GAMES';

SELECT SUM(S.QUANTITY) AS TOTAL_GAMES_SOLD FROM SALES AS S
INNER JOIN PRODUCTS AS P ON P.PRODUCTID = S.PRODUCTID
INNER JOIN CATEGORIES AS C ON C.CATEGORYID = P.CATEGORYID
WHERE C.NAME LIKE 'GAMES';

SELECT COUNT(P.NAME) TOTAL_PRODUCTS_WITHOUT_SALES FROM PRODUCTS AS P
LEFT JOIN SALES AS S ON S.PRODUCTID=P.PRODUCTID
WHERE S.PRODUCTID IS NULL;

SELECT AVG(R.RATING) AS AVERAGE_GAME_RATING  FROM REVIEWS AS R
INNER JOIN PRODUCTS AS P ON P.PRODUCTID=R.PRODUCTID
INNER JOIN CATEGORIES AS C ON C.CATEGORYID=P.CATEGORYID
WHERE C.NAME LIKE 'GAMES';

SELECT SUM(S.QUANTITY) AS QUANTITY, C.NAME AS CATEGORY FROM CATEGORIES AS C
INNER JOIN PRODUCTS AS P ON P.CATEGORYID = C.CATEGORYID
INNER JOIN SALES AS S ON S.PRODUCTID = P.PRODUCTID
GROUP BY CATEGORY
ORDER BY QUANTITY desc limit 1,1; 

SELECT * FROM SALES
ORDER BY SALES.DATE;

SELECT COUNT(DISTINCT S.PRODUCTID) AS SOLD_IN_2015 FROM SALES AS S
WHERE S.PRICEPERUNIT > 50.00 AND NOT (S.DATE > '2015-12-31 15:25:00' OR S.DATE < '2015-01-01 15:25:03');

SELECT D.NAME AS DEPARTMENT, SUM(S.QUANTITY*S.PRICEPERUNIT) AS REVENUE FROM DEPARTMENTS AS D
INNER JOIN CATEGORIES AS C ON C.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN PRODUCTS AS P ON P.CATEGORYID = C.CATEGORYID
INNER JOIN SALES AS S ON P.PRODUCTID = S.PRODUCTID
GROUP BY department
ORDER BY REVENUE
LIMIT 1;

SELECT E.FIRSTNAME FROM EMPLOYEES AS E
INNER JOIN SALES AS S ON S.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN PRODUCTS AS P ON P.PRODUCTID = S.PRODUCTID
INNER JOIN CATEGORIES AS C ON C.CATEGORYID = P.CATEGORYID
INNER JOIN DEPARTMENTS AS D ON D.DEPARTMENTID = C.DEPARTMENTID
WHERE D.NAME LIKE 'SMALL ELECTRONICS'
GROUP BY S.EMPLOYEEID
ORDER BY SUM(S.QUANTITY*S.PRICEPERUNIT) DESC
LIMIT 1;